# generated by datamodel-codegen:
#   filename:  CarbonFootprintForBatteries-schema.json
#   timestamp: 2026-01-06T16:16:43+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel


class LifecycleStage(Enum):
    RawMaterialExtraction = 'RawMaterialExtraction'
    MainProduction = 'MainProduction'
    Distribution = 'Distribution'
    Recycling = 'Recycling'


class CarbonFootprintPerLifecycleStageEntity(BaseModel):
    lifecycleStage: LifecycleStage
    """
    The description of the life cycle stage 
    """
    carbonFootprint: float
    """
    Carbon footprint of the individual lifecycle stage
    """


class Model(BaseModel):
    batteryCarbonFootprint: float
    """
    The carbon footprint of the battery, calculated as kg of carbon dioxide equivalent per one kWh of the total energy provided by the battery over its expected service life, as declared in the Carbon Footprint Declaration.
    DIN DKE Spec 99100 chapter reference: 6.3.2
    """
    carbonFootprintPerLifecycleStage: list[CarbonFootprintPerLifecycleStageEntity]
    """
    The carbon footprint of the battery as share of total Battery Carbon Footprint, differentiated per life cycle stages raw material extraction, battery production, distribution and recycling.

    DIN DKE Spec 99100 chapter reference: 
    6.3.3: Raw material extraction
    6.3.4: Main production
    6.3.5: Distrinution
    6.3.6: EoL/Recycling
    """
    carbonFootprintPerformanceClass: str
    """
    The carbon footprint performance class that the relevant battery model per manufacturing plant corresponds to.

    DIN DKE Spec 99100 chapter reference:  6.3.7
    """
    carbonFootprintStudy: AnyUrl
    """
    A web link to get access to a public version of the study supporting the carbon footprint values.

    DIN DKE Spec 99100 chapter reference:  6.3.8
    """
    absoluteCarbonFootprint: float | None = None
    """
    As a non-mandatory data attribute, the battery passport should include the battery carbon footprint in absolute terms.

    The absolute battery carbon footprint should be calculated as kilograms of carbon dioxide equivalent, without reference to the functional unit as prescribed by the battery regulation.

    DIN DKE Spec 99100 chapter reference: 6.3.10
    """
