# generated by datamodel-codegen:
#   filename:  Circularity-schema.json
#   timestamp: 2026-01-06T16:16:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AnyUrl, BaseModel, Field


class Documenttype(Enum):
    BillOfMaterial = 'BillOfMaterial'
    Model3D = 'Model3D'
    DismantlingManual = 'DismantlingManual'
    RemovalManual = 'RemovalManual'
    OtherManual = 'OtherManual'
    Drawing = 'Drawing'


class RecycledMaterial(Enum):
    Cobalt = 'Cobalt'
    Nickel = 'Nickel'
    Lithium = 'Lithium'
    Lead = 'Lead'
    Cobalt_1 = 'Cobalt'
    Nickel_1 = 'Nickel'
    Lithium_1 = 'Lithium'
    Lead_1 = 'Lead'


class PostalAddress(BaseModel):
    addressCountry: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """
    postalCode: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """
    streetAddress: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """


class DismantlingandRemovalDocumentation(BaseModel):
    documentType: Documenttype
    """
    Describes type for document e.g. Dismantling manual
    """
    mimeType: str
    """
    Defines internet media typ to determin how to interpret the documentURL
    """
    documentURL: AnyUrl
    """
    Link to document
    """


class EndOfLifeInformationEntity(BaseModel):
    wastePrevention: AnyUrl
    """
    Prevention and management of waste batteries: Point (a) of Article 60(1): Information on the role of end-users in contributing to waste prevention, including by information on good practices and recommendations concerning the use of batteries aiming at extending their use phase and the possibilities of re-use, preparing for re-use, preparing for repurpose, repurposing and remanufacturing
    """
    separateCollection: AnyUrl
    """
    Prevention and management of waste batteries: Point (b) of Article 60(1): Information on the role of end-users in contributing to the separate collection of waste batteries in accordance with their obligations under Article 51 so as to allow their treatment
    """
    informationOnCollection: AnyUrl
    """
    Prevention and management of waste batteries: Point (c) of Article 60(1): information on the separate collection, the take back, the collection points and preparing for re-use, preparing for repurposing, and recycling operations available for waste batteries
    """


class RecycledContentEntity(BaseModel):
    preConsumerShare: Annotated[float, Field(ge=0.0, le=100.0)]
    """
    Recycled material share from pre-consumer waste (manufacturing waste, excluding run-around scrap) of the active material.
    """
    recycledMaterial: RecycledMaterial
    """
    Name of recycled material
    """
    postConsumerShare: Annotated[float, Field(ge=0.0, le=100.0)]
    """
    Recycled material share from post-consumer waste (end-of-life scrap) of the active material.
    """


class SafetyMeasuresEntity(BaseModel):
    safetyInstructions: AnyUrl
    """
    - Safety measures. - Necessary safety instructions to handle waste batteries, including in relation to the risks associated with, and the handling of, batteries containing lithium.
    """
    extinguishingAgent: list[str]
    """
    Usable extinguishing agents refering to classes of extinguishers (A, B, C, D, K).EUBR: Annex XIII (1a) ? Annex VI Part A (9)
    """


class AddressOfSupplier(PostalAddress):
    pass


class ComponentEntity(BaseModel):
    partName: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """
    partNumber: str
    """
    Part Number of Component
    """


class EndOfLifeInformation(EndOfLifeInformationEntity):
    pass


class SafetyMeasures(SafetyMeasuresEntity):
    pass


class SparePartSupplierEntity(BaseModel):
    nameOfSupplier: str
    """
    Name of Supplier
    """
    addressOfSupplier: AddressOfSupplier
    """
    Postal address of supplier for spare parts.
    """
    emailAddressOfSupplier: Annotated[
        str, Field(pattern='^[\\w.-]+@[\\w.-]+\\.[A-Za-z]{2,}$')
    ]
    """
    E-mail address of supplier for spare parts.
    """
    supplierWebAddress: AnyUrl
    """
    Web address of supplier for spare parts.
    """
    components: list[ComponentEntity]
    """
    Components available at supplier
    """


class Model(BaseModel):
    dismantlingAndRemovalInformation: list[DismantlingandRemovalDocumentation]
    """
    Dismantling and Removal information, including at least:- Exploded diagrams of the battery system/pack showing the location of battery cells- Disassembly sequences- Type and number of fastening techniques to be unlocked- Tools required for disassembly- Warnings if risk of damaging parts exists- Amount of cells used and layout. BR Annex XIII (2c)

    DIN DKE Spec 99100 chapter reference: 6.6.1.2
    """
    sparePartSources: list[SparePartSupplierEntity]
    """
    Contact details of sources for replacement spares. Postal address, including name and brand names, postal code and place, street and number, country, telephone, if any. BR Annex XIII (2b)

    DIN DKE Spec 99100 chapter reference: 6.6.1.3
    """
    recycledContent: list[RecycledContentEntity]
    """
    Share of material recovered from waste present in active materials for each battery model per year and per manufacturing plant.

    DIN DKE Spec 99100 chapter reference:  6.6.2.3 - 6.6.2.10
    """
    safetyMeasures: SafetyMeasures
    """
    Safety measures and instructions should also take past negative and extreme events as well as the separate data attributes ?battery status? and ?battery composition/chemistry? into account.

    DIN DKE Spec 99100 chapter reference: 6.6.1.5
    """
    endOfLifeInformation: EndOfLifeInformation
    """
    Producer or producer responsibility organisations shall make information available to distributors and end-users on: the role of end-users in contributing to waste prevention, including by information on good practices and recommendations concerning the use of batteries aiming at extending their use phase and the possibilities of re-use, preparing for re-use, preparing for repurpose, repurposing and remanufacturing.

    DIN DKE Spec 99100 chapter reference: 6.6.3.2 - 6.6.3.4
    """
    renewableContent: float
    """
    Share of renewable material content. A renewable material is a material made of natural resources that can be replenished. 

    DIN DKE Spec 99100 chapter reference: 6.6.2.11
    """
