# generated by datamodel-codegen:
#   filename:  GeneralProductInformation-schema.json
#   timestamp: 2026-01-06T16:11:05+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class BatteryCategoryEnum(Enum):
    lmt = 'lmt'
    ev = 'ev'
    industrial = 'industrial'
    stationary = 'stationary'


class BatteryStatusEnumeration(Enum):
    Original = 'Original'
    Repurposed = 'Repurposed'
    Reused = 'Reused'
    Remanufactured = 'Remanufactured'
    Waste = 'Waste'


class PostalAddressEntity(BaseModel):
    addressCountry: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """
    postalCode: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """
    streetAddress: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """


class PostalAddress(PostalAddressEntity):
    pass


class ManufacturingPlace(PostalAddressEntity):
    pass


class ContactInformationEntity(BaseModel):
    contactName: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """
    postalAddress: PostalAddress
    identifier: str
    """
    Not demanded by the EU Battery Regulation
    """
    emailAddress: Annotated[
        str | None, Field(pattern='^[w.-]+@[w.-]+.[A-Za-z]{2,}$')
    ] = None
    """
    email address
    """
    webAddress: AnyUrl | None = None
    """
    Web address.
    """


class ManufacturerInformation(ContactInformationEntity):
    pass


class OperatorInformation(ContactInformationEntity):
    pass


class Model(BaseModel):
    productIdentifier: str
    """
    Unique identifier allowing for the unambiguous identification of each individual battery and hence each corresponding battery passport (exploration of a potential additional battery passport identifier (not requried per Battery Regulation) ongoing).
    DIN DKE Spec chapter reference: 6.1.2.2
    """
    batteryPassportIdentifier: Annotated[
        str, Field(pattern='^urn:[a-z0-9]+:[a-z0-9]+$')
    ]
    """
    Unique identifier allowing for the unambiguous identification of each individual battery and hence each corresponding battery passport (exploration of a potential additional battery passport identifier (not requried per Battery Regulation) ongoing).
    """
    batteryCategory: BatteryCategoryEnum
    """
    Categories relevant for the battery passport: LMT battery, ?electric vehicle battery, stationary or other industrial battery >2kWh.

    DIN DKE Spec chapter reference: 6.1.3.5
    """
    manufacturerInformation: ManufacturerInformation
    """
    Unambiguous identification of the manufacturer of the battery, suggested via a unique operator identifier (as "unique string of characters for the identification of actors involved in the value chain of products", ESPR Art. 2(32)). 

    DIN DKE Spec chapter reference: 6.1.2.4
    """
    manufacturingDate: AwareDatetime
    """
    The manufacturing date should not only relate to the battery model, but to the battery item.

    The date code should comply with DIN ISO 8601 1:2020 12 and ISO 8601 2:2019.

    DIN DKE Spec chapter reference: 6.1.3.2
    """
    batteryStatus: BatteryStatusEnumeration
    """
    Lifecycle status of the battery. Status defined from a list, with the options suggested as follows: 'original', 'repurposed', 'reused', 'remanufactured', 'waste'.

    DIN DKE Spec chapter reference: 6.1.3.7
    """
    batteryMass: float
    """
    Mass of the entire battery in kilograms. Voluntary: if the battery is defined on pack or module level: also weight of the modules and/or cells.

    DIN DKE Spec chapter reference: 6.1.3.6
    """
    manufacturingPlace: ManufacturingPlace
    """
    Unambiguous identification of the manufacturing facility (e.g. country, city, street, building (if needed)), suggested via a unique facility identifier (as "unique string of characters for the identification of locations or buildings involved in the value chain of a product or used by actors involved in the value chain of a product", ESPR Art. 2(33)).

    DIN DKE Spec chapter reference: 6.1.3.1
    """
    operatorInformation: OperatorInformation
    """
    State the name, trade name or mark, postal address, web ad-dress, e-mail address. Suggested reporting via a unique operator identifier (see requirements of unique battery identifier).

    DIN DKE Spec chapter reference: 6.1.2.3
    """
    puttingIntoService: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Where appropriate, the battery passport must include information on the date of putting the battery into service. BR Annex VI Part A (1); Art. 3(33); Art. 38(7); ESPR Art. 2(32)

    DIN DKE Spec chapter reference: 6.1.3.3
    """
    warrentyPeriod: Annotated[
        str,
        Field(
            pattern='--(0[1-9]|1[0-2])(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    The battery passport must include information about the period for which the commercial warranty applies.

    DIN DKE Spec chapter reference: 6.1.3.4
    """
