# generated by datamodel-codegen:
#   filename:  Labeling-schema.json
#   timestamp: 2026-01-06T16:17:19+00:00

from __future__ import annotations

from enum import Enum

from pydantic import AnyUrl, BaseModel


class LabelingSubject(Enum):
    SeparateCollection = 'SeparateCollection'
    HazardousMaterial = 'HazardousMaterial'
    CarbonFootPrint = 'CarbonFootPrint'
    ExtinguishingAgent = 'ExtinguishingAgent'


class MultiLanguageText(BaseModel):
    pass


class LabelingEntity(BaseModel):
    labelingSymbol: AnyUrl
    """
    The path of a resource.
    """
    labelingMeaning: MultiLanguageText
    """
    Explanation of the meaning of all symbols and labels (including separate collection; cadmium and lead; and carbon footprint and carbon footprint performance class symbols; and symbols and labels printed on batteries or their accompanying documents but not accessible via the battery passport).
    """
    labelingSubject: LabelingSubject
    """
    Short name of required labeling subjects
    """


class Model(BaseModel):
    declarationOfConformity: AnyUrl
    """
    A battery passport must include the EU declaration of conformity.

    The regulation specifies the following requirements regarding the EU declaration of conformity (see BattReg Annex XIII (1r) and BattReg Article 18 (2)):

    - The EU declaration of conformity has the model structure set out in Annex IX.
    - The EU declaration of conformity must contain the elements specified in the relevant modules set out in Annex VIII.
    - The EU declaration of conformity must be kept up to date.
    - It is translated into the language or languages required by the Member State in which the battery is placed or made available on the market or put into service.
    - It must be drawn up in electronic format and, where requested, it must be provided in paper format.

    DIN DKE Spec chapter reference: 6.2.7
    """
    resultOfTestReport: AnyUrl
    """
    URL to a document that includes results of tests reports proving compliance in the market conformity assessment procedure with the requirements as per the technical documentation (Art. 7-10, Art. 12-14 and due diligence policies ).

    DIN DKE Spec chapter reference 6.2.8
    """
    labels: list[LabelingEntity]
    """
    'Separate collection' or 'WEEE label' indicating that a product should not be discarded as unsorted waste but must be sent to separate collection facilities for recovery and recycling. To be printed on the physical label and displayed via the battery passport, suggested to be translated also to text to ensure machine readability.

    DIN DKE Spec chapter reference: 

    6.2.2 Separate collection
    6.2.3 Material symbol for Cadmium and Lead
    6.2.4 Carbon Footprint perfromance class
    6.2.5 Extinguishing agent
    """
