# generated by datamodel-codegen:
#   filename:  MaterialComposition-schema.json
#   timestamp: 2026-01-06T16:16:59+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field


class HazardousSubstanceClassChrateristicEnum(Enum):
    AcuteToxicity = 'AcuteToxicity'
    SkinCorrosionOrIrritation = 'SkinCorrosionOrIrritation'
    EyeDamageOrIrritation = 'EyeDamageOrIrritation'


class BatteryLocationEntity(BaseModel):
    componentName: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """
    componentId: str | None = None
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """


class BatteryChemistryEntity(BaseModel):
    shortName: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """
    clearName: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """


class BatteryMaterialLocation(BatteryLocationEntity):
    pass


class HubstanceSubstanceLocationEntity(BatteryLocationEntity):
    pass


class BatteryChemistryEntityList(BatteryChemistryEntity):
    pass


class BatteryMaterialEntity(BaseModel):
    batteryMaterialLocation: BatteryMaterialLocation
    """
    Battery component that relates to the material
    """
    batteryMaterialIdentifier: Annotated[str, Field(pattern='^\\d{2,7}-\\d{2}-\\d{1}$')]
    """
    CAS Number 
    """
    batteryMaterialName: str
    """
    Clear name of Material
    """
    batteryMaterialMass: float
    """
    Weight of component material
    """
    isCriticalRawMaterial: bool
    """
    The battery passport must contain information on the critical raw materials present in the battery.

    The information on the critical raw materials must also be provided on the battery label.
    Per Annex VI, Part A(10), critical raw materials must be reported if present in the battery in a concentration of more than 0,1 % weight by weight. 
    """


class HazardousSubstanceEntity(BaseModel):
    hazardousSubstanceClass: HazardousSubstanceClassChrateristicEnum
    """
    Battery Regulation narrows reporting to substances falling under defined hazard classes and categories of the CLP regulation.
    """
    hazardousSubstanceName: str
    """
    Clear name of hazardous substance
    """
    hazardousSubstanceConcentration: float
    """
    Concentration of hazardous substance
    """
    hazardousSubstanceImpact: list[str]
    """
    Impact statements based on, e.g., REACH or GHS for all hazard classes applicable to substances in the battery.
    """
    hazardousSubstanceLocation: HubstanceSubstanceLocationEntity
    """
    Hazardous substances (No. 19-23): Location on a (sub-)component-level of all hazardous substances (as ?any substance that poses a threat to human health and the environment?). Suggested via a unique identifier or nomenclature.
    """
    hazardousSubstanceIdentifier: Annotated[
        str, Field(pattern='^\\d{2,7}-\\d{2}-\\d{1}$')
    ]
    """
    CAS identifier of hazardous substance
    """


class Model(BaseModel):
    batteryChemistry: BatteryChemistryEntityList
    """
    Composition of a product in general terms by specifying the cathode and anode active material as well as electrolyte.

    DIN DKE Spec 99100 chapter reference: 6.5.2
    """
    batteryMaterials: list[BatteryMaterialEntity]
    """
    "Component materials used" (No. 17.a-c): Naming the materials (as a composition of substances) in cathode, anode, electrolyte according to public standards, including specification of the corresponding component (i.e., cathode, anode, or electrolyte). We suggest a reporting threshold of 0.1 % weight by weight.

    DIN DKE Spec 99100 chapter reference: 6.5.3-6.5.4
    """
    hazardousSubstances: list[HazardousSubstanceEntity]
    """
    "Hazardous substances" (No 20.a-e): Name (agreed substance nomenclature, e.g. IUPAC or chemical name) all hazardous substance (as ?any substance that poses a threat to human health and the environment?). Suggested above 0.1 % weight by weight within each (sub-)component.

    DIN DKE Spec 99100 chapter reference: 6.5.4 - 6.5.6
    """
