# generated by datamodel-codegen:
#   filename:  PerformanceAndDurability-schema.json
#   timestamp: 2026-01-06T16:17:11+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AnyUrl, BaseModel, Field


class BatteryComponent(Enum):
    pack = 'pack'
    module = 'module'
    cell = 'cell'


class CapacityFadeEntity(BaseModel):
    capacityFadeValue: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class CapacityThroughputEntity(BaseModel):
    capacityThroughputValue: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class CurrentSelfDischargingRateEntity(BaseModel):
    currentSelfDischargingRateEntity: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class EvolutionOfSelfDischargeEntity(BaseModel):
    evolutionOfSelfDischargeEntityValue: float


class InternalResistanceEntity(BaseModel):
    ohmicResistance: float
    """
    Initial (Pre-Use) internal resistance on battery pack level. 

    Definition of internal resistance should differ from regulation definition, as "opposition" is not an electrotechnical term and may be based on IEV 131-12-04: "internal resistance means the absolute value of the quotient of the voltage drop between the terminals by the electric current increase in the battery circuit during a current pulse"
    """
    batteryComponent: BatteryComponent


class InternalResistanceIncreaseEntity(BaseModel):
    internalResistanceIncreaseValue: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """
    batteryComponent: BatteryComponent


class NegativeEventEntity(BaseModel):
    negativeEvent: str
    """
    Describes a Property which contains plain text. This is intended exclusively for human readable strings, not for identifiers, measurement values, etc.
    """
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class NumberOfFullCyclesEntity(BaseModel):
    numberOfFullCyclesValue: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class PowerCapabilityAtEntity(BaseModel):
    atSoC: float
    powerCapabilityAt: float


class RemainingCapacityEntity(BaseModel):
    remainingCapacityValue: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class RemainingEnergyEntity(BaseModel):
    remainingEnergyalue: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class RemainingRoundTripEnergyEfficiencyEntity(BaseModel):
    remainingRoundTripEnergyEfficiencyValue: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class StateOfCertifiedEnergyEntity(BaseModel):
    stateOfCertifiedEnergyValue: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class StateOfChargeEntity(BaseModel):
    stateOfChargeValue: float
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class TemperatureConditionsEntity(BaseModel):
    timeExtremeHighTemp: float
    """
    Cumulated time spent above the given upper boundary of temperature.
    """
    timeExtremeLowTemp: float
    """
    Cumulated time spent below the given lower boundary of temperature.
    """
    timeExtremeHighTempCharging: float
    """
    Cumulated time spent above the given upper boundary of temperature during Charging.
    """
    timeExtremeLowTempCharging: float
    """
    Cumulated time spent below the given lower boundary of temperature during charging.
    """
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class RemainingPowerCapabilityDynamicAt(PowerCapabilityAtEntity):
    rPCLastUpdated: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Describes a Property which contains the date and time with an optional timezone.
    """


class CapacityFade(CapacityFadeEntity):
    pass


class CapacityThroughput(CapacityThroughputEntity):
    pass


class CurrentSelfDischargingRate(CurrentSelfDischargingRateEntity):
    pass


class EvolutionOfSelfDischarge(EvolutionOfSelfDischargeEntity):
    pass


class NumberOfFullCycles(NumberOfFullCyclesEntity):
    pass


class RemainingCapacity(RemainingCapacityEntity):
    pass


class RemainingEnergy(RemainingEnergyEntity):
    pass


class RemainingRoundTripEnergyEfficiency(RemainingRoundTripEnergyEfficiencyEntity):
    pass


class StateOfCertifiedEnergy(StateOfCertifiedEnergyEntity):
    pass


class StateOfCharge(StateOfChargeEntity):
    pass


class TemperatureInformation(TemperatureConditionsEntity):
    pass


class RemainingPowerCapabilityValue(RemainingPowerCapabilityDynamicAt):
    pass


class BatteryTechnicalPropertiesEntity(BaseModel):
    originalPowerCapability: list[PowerCapabilityAtEntity]
    """
    Pre-use power capability: Definition of power capability as given in Battery Regulation. 
    Annex IV Part B, point 4 --> measurement at 80 % and 20 % SoC required. This requirement may not be implementable for remaining power capability and power fade(see below). It, thus, should be reviewed together with SoC definition.

    DIN DKE Spec 99100 chapter reference: 6.7.3.2


    """
    ratedMaximumPower: float
    """
    This data point describes the value of maximum permitted power the battery is rated for and reflects the data relevant for power limits.

    DIN DKE Spec 99100 chapter reference: 6.7.3.2
    """
    powerCapabilityRatio: float
    """
    Provides information on nominal/recommended charge rate (C-rate); equal to regulation definition.
    """
    ratedEnergy: float
    """
    The certified usable battery energy is the usable battery energy according to the procedure in the UN GTR No 22 as determined during the certification of the vehicle.

    DIN DKE Spec 99100 chapter reference: 6.7.2.5
    """
    expectedNumberOfCycles: Annotated[
        float, Field(ge=-9.223372036854776e18, le=9.223372036854776e18)
    ]
    """
    Expected battery lifetime expressed in cycles.
    The exception for non-cycle applications in Article 10 appears sensible, but is not included in the Annex XIII provision.
    The data attribute is defined by measurement conditions of the cycle-life test such as the C-Rate (see below) and the depth of discharge in the cycle-life test

    DIN DKE Spec 99100 chapter reference: 6.7.6.3
    """
    initialSelfDischarge: float
    """
    Initial self-discharge in % of capacity per unit of time in defined conditions (temperature range etc) as pre-use metric. 

    DIN DKE Spec 99100 chapter reference: 6.7.4.6
    """
    roundtripEfficiency: float
    """
    Energy round trip efficiency is the ratio of the net energy delivered by a battery during a discharge test to the total energy required to restore the initial state of charge by a standard charge (see BattReg Annex IV (6)).

    DIN DKE Spec 99100 chapter reference: 6.7.4.2
    """
    ratedCapacity: float
    """
    ´┐¢Rated capacity´┐¢ is the total number of ampere-hours (Ah) that can be withdrawn from a fully charged battery under reference conditions (see BattReg Annex IV (1)).

    DIN DKE Spec 99100 chapter reference: 6.7.2.2
    """
    initialInternalResistance: list[InternalResistanceEntity]
    """
    The battery passport can include additional information about the initial internal resistance on battery module level, if available. It should be defined and calculated analogously as the requirements on battery pack level above.

    DIN DKE Spec 99100 chapter reference: 6.7.5.2
    """
    expectedLifetime: Annotated[float, Field(ge=-32768.0, le=32767.0)]
    """
    The battery passport must include information about the expected battery lifetime in calendar years.

    The update interval must be upon placement on the market and upon change of the battery status.

    DIN DKE Spec 99100 chapter reference: 6.7.6.2
    """
    cRate: float | None = None
    """
    As a non-mandatory data point the battery passport should include the ratio between nominal battery power in W and battery energy in Wh. It aims to provide an indication of the applicable discharge and charge rate in terms of rated capacity (C-rate) (see BattReg Annex IV Part B(2)).

    The update interval should be upon placement on the market and upon change of the battery status.

    DIN DKE Spec 99100 chapter reference: 6.7.3.6
    """
    nominalVoltage: float
    """
    Nominal voltage the battery is rated for.

    DIN DKE Spec 99100 chapter reference: 6.7.2.11
    """
    minimumVoltage: float
    """
    Minimum voltage the battery is rated for.

    DIN DKE Spec 99100 chapter reference: 6.7.2.9
    """
    maximumVoltage: float
    """
    Maximum voltage the battery is rated for.

    DIN DKE Spec 99100 chapter reference: 6.7.2.10
    """
    capacityThresholdForExhaustion: float
    """
    The percentage of SOCE, above which the battery is still considered operational as EV battery in its current life, as provided by the economic operator.

    DIN DKE Spec 99100 chapter reference: 6.7.6.9
    """
    lifetimeReferenceTest: AnyUrl
    """
    The exception for non-cycle applications as mentioned in "Expected lifetime: Number of charge-discharge cycles" should apply to this data attribute as well.

    DIN DKE Spec 99100 chapter reference: 6.7.6.5
    """
    cRateLifeCycleTest: float
    """
    The C-rate should be provided separately for both the charge and discharge of the battery, if applicable.

    The exception for non-cycle applications as mentioned in "Expected lifetime: Number of charge-discharge cycles" should apply to this data attribute as well.

    DIN DKE Spec 99100 chapter reference: 6.7.6.6
    """
    temperatureRangeIdleState: Annotated[float, Field(ge=-20.0, le=60.0)]
    """
    Upper an lower boundary of the surrounding temperature range, which the battery can safely withstand. 

    DIN DKE Spec 99100 chapter reference: 6.7.6.3-4
    """


class RemainingPowerCapabilityEntity(BaseModel):
    remainingPowerCapabilityValue: RemainingPowerCapabilityValue
    lastUpdate: Annotated[
        str,
        Field(
            pattern='-?([1-9][0-9]{3,}|0[0-9]{3})-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T(([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](\\.[0-9]+)?|(24:00:00(\\.0+)?))(Z|(\\+|-)((0[0-9]|1[0-3]):[0-5][0-9]|14:00))?'
        ),
    ]
    """
    Timestamp for dynamic data attributes show the last update time.
    """


class BatteryTechnicalProperties(BatteryTechnicalPropertiesEntity):
    pass


class BatteryConditionEntity(BaseModel):
    energyThroughput: float
    """
    The data attribute should be reported as measured for further potential processing. In addition, the normalisation by capacity may add a further useful value that ensures comparability among battery sizes.

    DIN DKE Spec 99100 chapter reference: 6.7.6.7
    """
    capacityThroughput: CapacityThroughput
    """
    The data attribute should be reported as measured for further potential processing. In addition, the normalisation by capacity may add a further useful value that ensures comparability among battery sizes.

    DIN DKE Spec 99100 chapter reference: 6.7.6.8
    """
    numberOfFullCycles: NumberOfFullCycles
    """
    Number of (full) charging and discharging cycles.

    DIN DKE Spec 99100 chapter reference: 6.7.6.3
    """
    stateOfCertifiedEnergy: StateOfCertifiedEnergy
    """
    Definition based on UNECE GTR 22: The measured or on-board UBE performance at a specific point in its lifetime, expressed as a percentage of the certified usable battery energy.

    DIN DKE Spec 99100 chapter reference: 6.7.2.7
    """
    capacityFade: CapacityFade
    """
    The capacity fade is the ´┐¢Decrease over time and upon usage in the amount of charge that a battery can deliver at the rated voltage, with respect to the original rated capacity´┐¢ (see BattReg Annex IV (2)) as declared by the manufacturer.

    DIN DKE Spec 99100 chapter reference: 6.7.2.4
    """
    remainingEnergy: RemainingEnergy
    """
    Definition from UNECE GTR 22, applicable only to EVs.
    The energy supplied by the battery from the beginning of the test procedure used for certification until the applicable break-off criterion of the test procedure used for certification is reached.

    DIN DKE Spec 99100 chapter reference: 6.7.2.6
    """
    remainingCapacity: RemainingCapacity
    """
    The in-use data attribute on capacity, corresponding with the definition of rated capacity.

    DIN DKE Spec 99100 chapter reference: 6.7.2.3
    """
    negativeEvents: list[NegativeEventEntity]
    temperatureInformation: TemperatureInformation
    """
    The battery passport must include periodically recorded information on the operating environmental conditions, including temperature.

    DIN DKE Spec 99100 chapter reference: 6.7.7.5 - 8
    """
    remainingPowerCapability: list[RemainingPowerCapabilityEntity]
    """
    '- Original power capability (in Watts) and limits, with temperature range when relevant.
    - The amount of energy that a battery is capable to provide over a given period of time under reference conditions.
    - Power capability at 80% and 20% state of charge.

    DIN DKE Spec 99100 chapter reference: 6.7.3.3
    """
    powerFade: float
    """
    ´┐¢Power fade (in %) means the decrease over time and upon usage in the amount of power that a battery can deliver at the rated voltage.´┐¢ (see BattReg Annex IV (4)).

    Power fade should be calculated using original and remaining power capability following the formula below:
    Pfade(x) = (1-P(x)) / PBOL" ´┐¢100" %" 
    where
    x 	is the aging parameter (e.g. storage time, number of cycles, etc.);
    P(x) 	is the power capability at aging parameter x;
    PBOL 	is the power capability at begin of life.

    DIN DKE Spec 99100 chapter reference: 6.7.3.4
    """
    roundTripEfficiencyFade: float
    """
    Energy round trip efficiency fade should be calculated using the initial round trip energy efficiency and remaining round trip energy efficiency following the formula below:

    RTEfade (x) = (1-RTE(x)) / RTEBOL  ´┐¢100" %" 
    where
    x 	is the aging parameter (e.g. storage time, number of cycles, etc.);
    RTE(x) 	is the round trip energy efficiency at aging parameter x;
    RTEBOL 	is the round trip energy efficiency at begin of life.

    DIN DKE Spec 99100 chapter reference: 6.7.4.5
    """
    evolutionOfSelfDischarge: EvolutionOfSelfDischarge
    """
    ´┐¢Evolution of self-discharge rates´┐¢ is the change of self-discharge over time and usage, as percentage calculated from the initial and current self-discharge rate.

    DIN DKE Spec 99100 chapter reference: 6.7.4.8
    """
    currentSelfDischargingRate: CurrentSelfDischargingRate
    """
    The current self-discharge rate is the change of the self-discharge rate in an idle state of the battery in reference conditions (temperature etc.) at aging parameter x, e.g. after a certain amount of storage time or, number of cycles.

    DIN DKE Spec 99100 chapter reference: 6.7.4.7
    """
    internalResistanceIncrease: list[InternalResistanceIncreaseEntity]
    """
    The internal resistance increase over time and upon usage should be defined based on the ratio of current and initial values as follows:
    Rincrease(x) = (R(x)  - RBOL) / RBOL ´┐¢ 100 %
    where
    x 	is the aging parameter (e.g. storage time, number of cycles, etc.;);
    R(x)	is the internal resistance at the aging parameter x; and
    RBOL	is the internal resistance at begin of life.

    The battery passport can include additional information about the internal resistance increase on battery cell and battery module level, if available. It should be defined and calculated analogously to the requirements on battery pack level above.

    DIN DKE Spec 99100 chapter reference: 6.7.5.3
    """
    roundTripEfficiencyat50PerCentCycleLife: float
    """
    Initial round trip energy efficiency shall be measured at reference conditions that include the specification of ´┐¢50 % of cycle-life´┐¢.

    Test methods and reference conditions should separately consider non-cycle applications and batteries with very long cycle-life.

    DIN DKE Spec 99100 chapter reference: 6.7.4.3

    """
    remainingRoundTripEnergyEfficiency: RemainingRoundTripEnergyEfficiency
    """
    The battery passport shall include information, where possible, about the remaining round trip energy efficiency as information on the state of health of the battery 

    The update frequency of remaining round trip energy efficiency should be aligned with the update frequency of round trip energy efficiency fade and should be provided upon change of the battery status.

    DIN DKE Spec 99100 chapter reference: 6.7.4.4
    """
    stateOfCharge: StateOfCharge
    """
    The Battery Pass consortium proposes to change the definition to: "available capacity in a battery expressed as a percentage of remaining capacity" to reflect use of SoC in practice.  

    DIN DKE Spec 99100 chapter reference: 6.7.2.8
    """


class BatteryCondition(BatteryConditionEntity):
    pass


class Model(BaseModel):
    batteryTechicalProperties: BatteryTechnicalProperties
    """
    This property covers all perfromance related properties
    """
    batteryCondition: BatteryCondition
    """
    '- Expected battery lifetime expressed in cycles, and reference test used.
    - Their expected life-time under the reference conditions for which they have been designed in terms of cycles, except for non-cycle applications, and calendar years.
    """
